name: Week 5 CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
   
jobs:
  lint_test:
    name: Lint test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test & lint tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest ansible ansible-lint

      - name: Ansible lint
        run: ansible-lint ansible/02_apache.yml
  deploy:
    name: Deploy de ansible-lint
    runs-on: self-hosted
    needs: [lint_test]
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Ansible
        run: |
          ansible-playbook ansible/02_apache.yml
          